fix: partial fix, still not working
current error:

```
$ just deploy foundation
NIXPKGS_ALLOW_INSECURE=1 NIXPKGS_ALLOW_UNFREE=1 sudo -E nixos-rebuild switch --flake .#foundation --impure
warning: $HOME ('/home/ghilston') is not owned by you, falling back to the one defined in the 'passwd' file ('/root')
warning: Git tree '/home/ghilston/Git/toolbox' is dirty
evaluation warning: nur.overlay has been replaced by nur.overlays.default
building the system configuration...
warning: $HOME ('/home/ghilston') is not owned by you, falling back to the one defined in the 'passwd' file ('/root')
warning: Git tree '/home/ghilston/Git/toolbox' is dirty
evaluation warning: nur.overlay has been replaced by nur.overlays.default
evaluation warning: ghilston profile: You are using

                      Home Manager version 24.11 and
                      Nixpkgs version 25.05.

                    Using mismatched versions is likely to cause errors and unexpected
                    behavior. It is therefore highly recommended to use a release of Home
                    Manager that corresponds with your chosen release of Nixpkgs.

                    If you insist then you can disable this warning by adding

                      home.enableNixpkgsReleaseCheck = false;

                    to your configuration.
[4/0/34 built, 9/9/28 copied (11.3/491.5 MiB), 2.7/111.4 MiB DL] building crate-napi-derive-2.16.13.tar.gzwarning: $HOME ('/home/ghilston') is not owned by you, falling back to the one defined in the 'passwd' file ('/root')
error: hash mismatch in fixed-output derivation '/nix/store/5hdsbgr6idacqvi86nbg3yb3cq4ga4vv-Claude-Setup-x64.exe.drv':
         specified: sha256-kzuvh0wl/saZlBHnpL0/EZItjsPpiX4kYrsd89A1sQo=
            got:    sha256-SOO1FkAfcOP50Z4YPyrrpSIi322gQdy9vk0CKdYjMwA=
error: 1 dependencies of derivation '/nix/store/jpz65h4y63vfbp32jxbw95n5s3vzjp4a-claude-desktop-0.7.7.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jgq7r98bkyqhyrgs9fz67571fs794wpg-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/4q62wgq1v2mjnyp5h72haq6yh0mxrpz3-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mf0pqhgf7blaj8rilir15wah42l8cx86-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/d4rfsfsif8l3v0ga89vxppcgm1iw7ndc-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kcmasyilil7x8n6v8g2qrwpbyf6ngcda-nixos-system-foundation-25.05.20241217.d3c42f1.drv' failed to build
error: Recipe `deploy` failed on line 4 with exit code 1
```